server:
  port: 8008

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/timeTracker-test
    username: sa
    password: