sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

install: true

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean
  - ./gradlew test
  - ./gradlew assemble

after_success:
  - sh .travis/deploy_dockerhub.sh
  - bash <(curl -s https://codecov.io/bash)
